version: '3'

services:
  db: 
    image: postgres
    restart: always
    container_name: rentx_db
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_DB: rentx
      POSTGRES_USER: rentx
      POSTGRES_PASSWORD: rentx
    volumes:
      - pgdata:/var/lib/postgresql/data
  app: 
    build: .
    container_name: rentx
    ports: 
      - 3000:3000
    volumes: 
      - .:/usr/app
volumes:
  pgdata:
